library("DESeq2")
x <- read.delim("6_deseq2_results/merged/GSE71519_merged.txt",header=TRUE,row.names="id",sep="	")
roundx <- round(x)
coldata <-read.delim("6_deseq2_results/merged/GSE71519_merged.meta",header=TRUE,row.names="id",sep="	")
dds <- DESeqDataSetFromMatrix(countData =roundx, colData = coldata, design =~group)
dds <- estimateSizeFactors(dds)
normalized_counts <- counts(dds, normalized=TRUE)
write.table(data.frame("id"=rownames(normalized_counts),normalized_counts), file="6_deseq2_results/norm/GSE71519_expression.deseq2_norm.txt", sep="	", quote=F, col.names=TRUE, row.names=FALSE)
des <- DESeq(dds)
res <- results(des, contrast=c("group","A","B"))
write.table(data.frame("id"=rownames(res),res), file="6_deseq2_results/deseq2/GSE71519_expression.deg.txt", sep="	", quote=F, col.names=TRUE, row.names=FALSE)
